---
title: "R Notebook"
output: html_notebook
---


```{r}
x <- "A. J. Burnett"
```



```{r}
x <- "A. J. Burnett"

gsub("([A-Z])\\.\\s([A-Z])\\.", "\\1.\\2.", x)
# [1] "A.J. Burnett"
```


```{r}
x <- c("PISCO-R009-SS", "PISCO-R027-LS", "PSCO-M0026-TS")
pattern <- "^(?!PSCO)"
grepl(pattern, x, perl = TRUE)

```

```{r}
x <- c("PISCO-R009-SS", "PISCO-R027-LS", "PSCO-M0026-TS")
pattern <- "[^PSCO]"
grepl(pattern, x, perl = TRUE)
```


```{r}
# replace any characters before the first dash
  x <- c("PISCO-R009-SS", "PISCO-R027-LS", "PSCO-M0026-TS")

  pattern <- "^[^-]+"
  repl_with <- "psco"

  gsub(pattern, repl_with, x, perl = TRUE)
```



```{r}
x <- c("PISCO-R009-SS", "PISCO-R027-LS", "PSCO-M0026-TS")

pattern <- "^(?:PSCO)"
repl_with <- "psco"

gsub(pattern, repl_with, x, perl = TRUE)
```


```{r}
x <- c("PISCO-R009-SS", "PISCO-R027-LS", "PSCO-M0026-TS")

pattern <- "[^[?PSCO]_]"
repl_with <- "psco"

gsub(pattern, repl_with, x, perl = TRUE)
```


```{r}
vec <- "hello world b x how are a z you"

gsub("(a|b|c)\\s+(x|y|z)","\\1_\\2", vec)
# [1] "hello world b_x how are a_z you"
```








```{r}
x <- c("PISCO-R009-SS", "PISCO-R027-LS", "PSCO-M0026-TS")

pattern <- "^(?!(PSCO))\\s+(PSCO)"
repl_with <- "\\1_\\2"

gsub(pattern, repl_with, x,perl = T)
```





https://stackoverflow.com/a/10038832/5270873

```{r}
# An example to replace a 15 at the start of the string (the ^ does this).
test <- c("15: .0234 , 12: .0151")
gsub("^15", "x", test)
# [1] "x: .0234 , 12: .0151"
```


```{r}
# A more general example to replace any number at the start of the string.
gsub("^([0-9]+)", "x", test)
# [1] "x: .0234 , 12: .0151"
```


```{r}
# An example to remove any number followed by a colon (:) and replace with an x and a colon

gsub("([0-9]+):","x:",test)
# [1] "x: .0234 , x: .0151"
```


https://stackoverflow.com/a/10046307/5270873
If you set perl=TRUE in gsub then you can use positive and negative look aheads or look behinds which might solve your problem, for example the pattern 15(?=:) will match a 15 that is followed by a colon (but will not match/replace the colon) and will not match any 15s that are not followed by a colon. The pattern `(?

```{r}
gsub("15(?=:)", "x", test, perl = TRUE)
```









```{r}
x <- c("foo_5", "bar_7")

gsub(".*_", "", x)
```


