# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hello_world <- function() {
    .Call(`_rNodal_oilwells_hello_world`)
}

outerproduct_cpp <- function(x) {
    .Call(`_rNodal_oilwells_outerproduct_cpp`, x)
}

#' Calculate inner and outer products
#'
#' @param x is a vector
#' @export
bothproducts <- function(x) {
    .Call(`_rNodal_oilwells_bothproducts`, x)
}

